version: "2.0"
services:
       
    mysql:
        image: mysql:5.7
        ports:
            - 3307:3306
        volumes:
            - ./database:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: changeme
            MYSQL_USER: dev
            MYSQL_PASSWORD: changeme
            MYSQL_DATABASE: byewait