version: "2.0"
services:
       
    byewait:
        build: .
        ports:
            - 8888:8888
        environment:
            MYSQL_ENDPOINT: changeme
            MYSQL_USER: dev
            MYSQL_PASSWORD: changeme
            MYSQL_DATABASE: byewait
        depends_on:
            - mysql

    mysql:
        image: mysql:5.7
        ports:
            - 3307:3306
        volumes:
            - ./database:/var/lib/mysql
            - ./db-scripts:/home

        environment:
            MYSQL_ROOT_PASSWORD: changeme
            MYSQL_USER: dev
            MYSQL_PASSWORD: changeme
            MYSQL_DATABASE: byewait
        